# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\projects\personal\test_task\src\ui\main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(770, 637)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(mainWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.sidebarLayout = QtWidgets.QVBoxLayout()
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.loadDataButton = QtWidgets.QPushButton(mainWidget)
        self.loadDataButton.setObjectName("loadDataButton")
        self.sidebarLayout.addWidget(self.loadDataButton)
        self.saveDataButton = QtWidgets.QPushButton(mainWidget)
        self.saveDataButton.setObjectName("saveDataButton")
        self.sidebarLayout.addWidget(self.saveDataButton)
        self.randomizeDataButton = QtWidgets.QPushButton(mainWidget)
        self.randomizeDataButton.setObjectName("randomizeDataButton")
        self.sidebarLayout.addWidget(self.randomizeDataButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sidebarLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.sidebarLayout)
        self.contentLayout = QtWidgets.QVBoxLayout()
        self.contentLayout.setObjectName("contentLayout")
        self.treeViewLayout = QtWidgets.QHBoxLayout()
        self.treeViewLayout.setObjectName("treeViewLayout")
        self.treeView = QtWidgets.QTreeView(mainWidget)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeView.setObjectName("treeView")
        self.treeViewLayout.addWidget(self.treeView)
        self.treeViewManageLayout = QtWidgets.QVBoxLayout()
        self.treeViewManageLayout.setObjectName("treeViewManageLayout")
        self.addNodeLayout = QtWidgets.QHBoxLayout()
        self.addNodeLayout.setObjectName("addNodeLayout")
        self.addTreeItemEdit = QtWidgets.QLineEdit(mainWidget)
        self.addTreeItemEdit.setObjectName("addTreeItemEdit")
        self.addNodeLayout.addWidget(self.addTreeItemEdit)
        self.addTreeItemButton = QtWidgets.QPushButton(mainWidget)
        self.addTreeItemButton.setObjectName("addTreeItemButton")
        self.addNodeLayout.addWidget(self.addTreeItemButton)
        self.treeViewManageLayout.addLayout(self.addNodeLayout)
        self.deleteTreeItemButton = QtWidgets.QPushButton(mainWidget)
        self.deleteTreeItemButton.setObjectName("deleteTreeItemButton")
        self.treeViewManageLayout.addWidget(self.deleteTreeItemButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.treeViewManageLayout.addItem(spacerItem1)
        self.treeViewLayout.addLayout(self.treeViewManageLayout)
        self.contentLayout.addLayout(self.treeViewLayout)
        self.graphLayout = QtWidgets.QVBoxLayout()
        self.graphLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.graphLayout.setObjectName("graphLayout")
        self.contentLayout.addLayout(self.graphLayout)
        self.mainLayout.addLayout(self.contentLayout)
        self.verticalLayout_4.addLayout(self.mainLayout)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "Form"))
        self.loadDataButton.setText(_translate("mainWidget", "Загрузить"))
        self.saveDataButton.setText(_translate("mainWidget", "Сохранить"))
        self.randomizeDataButton.setText(_translate("mainWidget", "Рандомное заполнение"))
        self.addTreeItemButton.setText(_translate("mainWidget", "Добавить элемент"))
        self.deleteTreeItemButton.setText(_translate("mainWidget", "Удалить элемент"))
